# Generated by Django 5.0.7 on 2024-08-17 22:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catgory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=22)),
                ('email', models.CharField(max_length=220)),
                ('PASSWORD', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default=True, max_length=100, null=True)),
                ('phone', models.DecimalField(decimal_places=2, default=True, max_digits=12)),
                ('picrure', models.ImageField(upload_to='upload/product/')),
                ('catgory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.catgory')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quntity', models.IntegerField(default=1)),
                ('addres', models.CharField(blank=True, default='', max_length=400)),
                ('phone', models.DecimalField(decimal_places=2, default=True, max_digits=12)),
                ('release_date', models.DateTimeField(default=datetime.datetime(2024, 8, 18, 3, 7, 7, 981018))),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.customer')),
            ],
        ),
    ]
