# Generated by Django 5.0.7 on 2024-08-18 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_order_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merch',
            name='phone',
        ),
        migrations.AddField(
            model_name='merch',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 14, 11, 38, 299846)),
        ),
    ]
