# Generated by Django 5.0.7 on 2024-09-01 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_merch_phone_merch_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 4, 51, 9, 517030)),
        ),
    ]
