# Generated by Django 5.0.7 on 2024-09-01 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_order_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 4, 58, 23, 1357)),
        ),
    ]
