# Generated by Django 5.0.7 on 2024-09-01 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_order_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merch',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 3, 54, 58, 870116)),
        ),
    ]
