# Generated by Django 5.0.7 on 2024-09-03 00:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_merch_is_sale_merch_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='merch',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='pages.merch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 5, 14, 22, 935038)),
        ),
    ]
