# Generated by Django 5.0.7 on 2024-09-03 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_order_merch_alter_order_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 5, 28, 44, 843926)),
        ),
    ]
