# Generated by Django 5.0.7 on 2024-09-03 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_order_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merch',
            old_name='picrure',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='order',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 5, 59, 25, 236767)),
        ),
    ]
