# Generated by Django 5.0.7 on 2024-09-03 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_rename_picrure_merch_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 6, 12, 14, 953740)),
        ),
    ]
