# Generated by Django 5.0.7 on 2024-09-03 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_order_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merch',
            old_name='picture',
            new_name='picturee',
        ),
        migrations.AlterField(
            model_name='order',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 6, 13, 23, 531736)),
        ),
    ]
